# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'DYTV-AlexanderZ-Swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DYTV-AlexanderZ-Swift

pod ‘Alamofire’
pod ‘Kingfisher’
end
